name: Publish CodeQL Packs

on:
  #push:
  #  branches: [main]
  workflow_dispatch:


jobs:
  queries:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        language: ["csharp", "java"] 

    steps:
      - uses: actions/checkout@v5
      - name: Check codeql-LANG-queries (src) pack
        id: check_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PUBLISHED_VERSION=$(gh api /orgs/Hug0Vincent/packages/container/qlinspector-${{ matrix.language }}-queries/versions --jq '.[0].metadata.container.tags[0]')
          CURRENT_VERSION=$(grep version ${{ matrix.language }}/src/qlpack.yml | awk '{print $2}')

          echo "Published version: $PUBLISHED_VERSION"
          echo "Local version: $CURRENT_VERSION"

          if [ "$PUBLISHED_VERSION" != "$CURRENT_VERSION" ]; then
            echo "publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup CodeQL
        id: init
        if: steps.check_version.outputs.publish == 'true'
        uses: github/codeql-action/init@v3

      - name: Publish codeql-LANG-queries (src) pack.
        if: steps.check_version.outputs.publish == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODEQL_PATH: ${{ steps.init.outputs.codeql-path }}
        run: |
          echo "Publishing codeql-${{ matrix.language }}-queries."
          "${CODEQL_PATH}" pack install "ql/${{ matrix.language }}/src"
          "${CODEQL_PATH}" pack publish "ql/${{ matrix.language }}/src"

  extensions:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        language: ["csharp"]

    steps:
      - uses: actions/checkout@v5

      - name: Check codeql-LANG-extensions (ext) pack
        id: check_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PUBLISHED_VERSION=$(gh api /orgs/githubsecuritylab/packages/container/codeql-${{ matrix.language }}-extensions/versions --jq '.[0].metadata.container.tags[0]')
          CURRENT_VERSION=$(grep version ${{ matrix.language }}/ext/qlpack.yml | awk '{print $2}')

          echo "Published version: $PUBLISHED_VERSION"
          echo "Local version: $CURRENT_VERSION"
          if [ "$PUBLISHED_VERSION" != "$CURRENT_VERSION" ]; then
            echo "publish=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup CodeQL
        id: init
        if: steps.check_version.outputs.publish == 'true'
        uses: github/codeql-action/init@v3

      - name: Publish codeql-LANG-queries (src) pack.
        if: steps.check_version.outputs.publish == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CODEQL_PATH: ${{ steps.init.outputs.codeql-path }}
        run: |
          echo "Publishing codeql-${{ matrix.language }}-queries."
          "${CODEQL_PATH}" pack install "ql/${{ matrix.language }}/ext"
          "${CODEQL_PATH}" pack publish "ql/${{ matrix.language }}/ext"